// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANgs587t-DQCUYseE_njmPRTEE8p0WRY',
    appId: '1:476455413432:web:a4cc3a0e61efddbcd2f64d',
    messagingSenderId: '476455413432',
    projectId: 'flutteritwe11',
    authDomain: 'flutteritwe11.firebaseapp.com',
    storageBucket: 'flutteritwe11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPiJJUVfEVDZnhhj3-ClwUd0aP_BqzfpE',
    appId: '1:476455413432:android:e46596bf70d48deed2f64d',
    messagingSenderId: '476455413432',
    projectId: 'flutteritwe11',
    storageBucket: 'flutteritwe11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kLBnbsSGHCaJDlQeutMEdI817lk1RHA',
    appId: '1:476455413432:ios:b10ece346e53f72bd2f64d',
    messagingSenderId: '476455413432',
    projectId: 'flutteritwe11',
    storageBucket: 'flutteritwe11.appspot.com',
    iosClientId: '476455413432-cg5l8hccujlsks8rm1qoved8djamu6ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbegins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8kLBnbsSGHCaJDlQeutMEdI817lk1RHA',
    appId: '1:476455413432:ios:b10ece346e53f72bd2f64d',
    messagingSenderId: '476455413432',
    projectId: 'flutteritwe11',
    storageBucket: 'flutteritwe11.appspot.com',
    iosClientId: '476455413432-cg5l8hccujlsks8rm1qoved8djamu6ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbegins',
  );
}
